// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-tile.cuh"

DECL_FATTN_TILE_CASE(512, 512);
DECL_FATTN_TILE_CASE_Q(512, 512, GGML_TYPE_Q4_0, GGML_TYPE_Q4_0);
DECL_FATTN_TILE_CASE_Q(512, 512, GGML_TYPE_Q8_0, GGML_TYPE_Q8_0);
